// Pixel-art character — 32×36 grid at 10px per pixel = 320×360 viewBox.
// Same identity cues as the soft style: buzz cut, full beard, olive skin,
// teal shirt, stud piercing in user's left ear (viewer's right).
//
// Pose strings: 32 chars per row, 36 rows. Each glyph maps to a colour.
// Empty space = '.'.
//
// Palette glyphs:
//   H = hair / beard / moustache (dark)
//   S = skin (face)
//   s = skin shade
//   b = brow (same hair colour)
//   E = eye (ink)
//   T = shirt (accent-ink)
//   t = shirt highlight (accent)
//   W = paper / collar
//   P = pants (dark grey)
//   O = outline / shoes (ink)
//   G = gold stud
//   L = laptop frame (light grey)
//   l = laptop screen (dark)
//   c = code line cyan
//   y = code line yellow
//   r = code line red
//   K = headphone cup (dark)
//   k = headphone speaker (accent)
//   m = mic boom
//   M = magnifier glass
//   R = megaphone red (yellow-orange)
//   Y = trophy gold
//   V = VR visor (paper)
//   v = VR lens (dark)
//   z = soundwave / sparkle (accent ink)

const PIX_PALETTE_LIGHT = {
  H: '#1f1812',
  S: '#cea27c',
  s: '#a98662',
  b: '#1f1812',
  E: '#0e0a06',
  T: '#0f4a5e',
  t: '#1e8aa8',
  W: '#f4efe2',
  P: '#1a1612',
  O: '#0e0a06',
  G: '#d2b16a',
  L: '#9aa3ad',
  l: '#0a1820',
  c: '#3fc3d4',
  y: '#e6c34d',
  r: '#e07050',
  K: '#222019',
  k: '#1e8aa8',
  m: '#222019',
  M: '#a2d6e0',
  R: '#d65a55',
  Y: '#e9c266',
  V: '#e6e1d3',
  v: '#0e0a06',
  z: '#1e8aa8',
};

const PIX_PALETTE_DARK = {
  ...PIX_PALETTE_LIGHT,
  W: '#2b2920',
  P: '#0a0805',
  // slightly brighter shirt in dark
  T: '#0d8aa3',
  t: '#3ad2e6',
};

// ---- POSES ----
// Standing front-facing base. Wave hand up on viewer-left (character's right hand).

const POSE_WAVE = `
................................
................................
................................
.....SS.........................
.....SS.....HHHHHHHH............
......TT...HHHHHHHHHH...........
......TT..HHHHHHHHHHHH..........
.......TT.HHHHHHHHHHHH..........
........TTHSSSSSSSSSSH..........
.........TTSbbSSSSbbSH..........
..........TSSEESSEESSH G........
..........TSSSSSSSSSSS..........
...........SSSSsSSSSSS..........
...........HMMMMMMMMMH..........
............HBBBBBBBH...........
............HBBBBBBBH...........
.............BBBBBBB............
..............BBBBB.............
..............SSSS..............
............TTTTTTTT............
...........TTTTTTTTTT...........
...........TTTWWWWTTT...........
..........TTTTTTTTTTTT..........
...........TTTTTTTTTT...........
...........TTTTTTTTTT...........
...........TTTTTTTTTT...........
...........TTTTTTTTTT.SS........
...........TTTTTTTTTT.TT........
...........TTTTTTTTTT.TT........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............OOOO.OOOO...........
................................
................................
`;

// Coding pose — both arms forward, typing on a laptop.
const POSE_CODE = `
................................
................................
................................
................................
............HHHHHHHH............
...........HHHHHHHHHH...........
..........HHHHHHHHHHHH..........
..........HHHHHHHHHHHH..........
..........HSSSSSSSSSSH..........
..........HSbbSSSSbbSH..........
..........HSEESSEESSSH G........
..........HSSSSSSSSSSS..........
...........SSSSsSSSSSS..........
...........HMMMMMMMMMH..........
............HBBBBBBBH...........
............HBBBBBBBH...........
.............BBBBBBB............
..............BBBBB.............
..............SSSS..............
............TTTTTTTT............
...........TTTTTTTTTT...........
...........TTTWWWWTTT...........
..........TTTTTTTTTTTT..........
.....LLLLLLLLLLLLLLLLLLLLL......
.....LlllllllllllllllllllL......
.....LlcccccccccccccccccccL.....
.....LlcccccccccyyyyyyyyycL.....
.....LlcccrrrrrcccccccccccL.....
.....LlccyyyyyyyycccccccccL.....
.....LlcccccccccccccccrrrrL.....
.....LLLLLLLLLLLLLLLLLLLLL......
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............OOOO.OOOO...........
................................
`;

// Voice pose — headphones + mic boom + tablet with waveform
const POSE_VOICE = `
................................
................................
................................
................................
............HHHHHHHH............
...........HHHHHHHHHH...........
.........KKHHHHHHHHHHKK.........
........KkkHHHHHHHHHHkkK........
........KkkHSSSSSSSSSSkkK.......
.........KKHSbbSSSSbbSHKK.......
..........HSEESSEESSSH G........
..........HSSSSSSSSSSS.mm.......
...........SSSSsSSSSSS..mm......
...........HMMMMMMMMMH...m......
............HBBBBBBBH....m......
............HBBBBBBBH....mm.....
.............BBBBBBB............
..............BBBBB.............
..............SSSS..............
............TTTTTTTT............
...........TTTTTTTTTT...........
...........TTTWWWWTTT.LLLLLL....
..........TTTTTTTTTTTTLllllL....
...........TTTTTTTTTT.LcyrycL...
...........TTTTTTTTTT.LcryrcL...
...........TTTTTTTTTT.LycrycL...
...........TTTTTTTTTT.LcrcrycL..
...........TTTTTTTTTT.LLLLLLL...
...........TTTTTTTTTT...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............OOOO.OOOO...........
................................
................................
`;

// Research pose — magnifier
const POSE_RESEARCH = `
................................
................................
................................
................................
............HHHHHHHH............
...........HHHHHHHHHH...........
..........HHHHHHHHHHHH..........
..........HHHHHHHHHHHH..........
..........HSSSSSSSSSSH..........
..........HSbbSSSSbbSH..........
..........HSEESSEESSSH G........
..........HSSSSSSSSSSS..........
...........SSSSsSSSSSS..........
...........HMMMMMMMMMH..........
............HBBBBBBBH...........
............HBBBBBBBH...........
.............BBBBBBB............
..............BBBBB.............
..............SSSS..............
............TTTTTTTT............
...........TTTTTTTTTT...........
...........TTTWWWWTTT.....MMM...
..........TTTTTTTTTTTT...MMMMM..
...........TTTTTTTTTT....MMMMM..
...........TTTTTTTTTT.....MMM...
...........TTTTTTTTTT.....OO....
...........TTTTTTTTTT......OO...
...........TTTTTTTTTT.......OO..
............TTTTTTTT.........OO.
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............OOOO.OOOO...........
................................
................................
`;

// Leadership pose — megaphone raised
const POSE_LEAD = `
................................
................................
................RRRR............
...............RRRRRRR..........
..............RRRRRRRRR.........
.............RRRRRRRRRRR........
............RRRRRRRRRRRRR.......
............HHHHHHHH..RRR.......
...........HHHHHHHHHHHRR........
..........HHHHHHHHHHHHHH........
..........HHHHHHHHHHHHHH........
..........HSSSSSSSSSSH..........
..........HSbbSSSSbbSH..........
..........HSEESSEESSSH G........
..........HSSSSSSSSSSS..........
...........SSSSsSSSSSS..........
...........HMMMMMMMMMH..........
............HBBBBBBBH...........
............HBBBBBBBH...........
.............BBBBBBB............
..............BBBBB.............
..............SSSS..............
............TTTTTTTT............
...........TTTTTTTTTT...........
...........TTTWWWWTTT...........
..........TTTTTTTTTTTT..........
...........TTTTTTTTTT...........
...........TTTTTTTTTT...........
...........TTTTTTTTTT...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............OOOO.OOOO...........
................................
................................
`;

// Win pose — both arms up, trophy above
const POSE_WIN = `
................................
.............YYYYYY.............
............YYYYYYYY............
............YYYYYYYY............
............YYYYYYYY............
............YYYYYYYY............
............OOOOOOOO............
.............OOOOOO.............
............OOOOOOOO............
...........OOOOOOOOOO...........
............HHHHHHHH............
...........HHHHHHHHHH...........
..........HHHHHHHHHHHH..........
..........HSSSSSSSSSSH..........
..........HSbbSSSSbbSH..........
..........HSEESSEESSSH G........
..........HSSSSSSSSSSS..........
...........SSSSsSSSSSS..........
...........HMMMMMMMMMH..........
............HBBBBBBBH...........
.............BBBBBBB............
..............BBBBB.............
..............SSSS..............
............TTTTTTTT............
...........TTTTTTTTTT...........
...........TTTWWWWTTT...........
..........TTTTTTTTTTTT..........
...........TTTTTTTTTT...........
...........TTTTTTTTTT...........
............TTTTTTTT............
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............OOOO.OOOO...........
................................
`;

// Study pose — sitting at desk reading
const POSE_STUDY = `
................................
................................
................................
................................
............HHHHHHHH............
...........HHHHHHHHHH...........
..........HHHHHHHHHHHH..........
..........HHHHHHHHHHHH..........
..........HSSSSSSSSSSH..........
..........HSbbSSSSbbSH..........
..........HSEESSEESSSH G........
..........HSSSSSSSSSSS..........
...........SSSSsSSSSSS..........
...........HMMMMMMMMMH..........
............HBBBBBBBH...........
............HBBBBBBBH...........
.............BBBBBBB............
..............BBBBB.............
..............SSSS..............
............TTTTTTTT............
...........TTTTTTTTTT...........
...........TTTWWWWTTT...........
..........TTTTTTTTTTTT..........
....cccc...TTTTTTTTTT...........
....yyyy...TTTTTTTTTT...........
....rrrr...TTTTTTTTTT...........
....WWWWWWWWWWWWWWWWWWWWWW......
....WlllllllllllllllllllW.......
....WWWWWWWWWWWWWWWWWWWWWW......
.............PPPP.PPPP..........
............OOOOOOOOOO..........
............OOOOOOOOOO..........
................................
................................
................................
................................
`;

// VR pose — visor over eyes, arms forward, controllers
const POSE_VR = `
................................
................................
................................
............vvvvvvvv............
............vvvvvvvv............
...........vvvvvvvvvv...........
..........VVVVVVVVVVVV..........
.........VVvvvvVVvvvvVV.........
.........VvvvvvVVvvvvvV.........
.........VVVVVVVVVVVVVV.........
..........HSSSSSSSSSSH G........
..........HSSSSSSSSSSS..........
...........SSSSsSSSSSS..........
...........HMMMMMMMMMH..........
............HBBBBBBBH...........
............HBBBBBBBH...........
.............BBBBBBB............
..............BBBBB.............
..............SSSS..............
............TTTTTTTT............
...........TTTTTTTTTT...........
...........TTTWWWWTTT...........
..........TTTTTTTTTTTT..........
.....TT....TTTTTTTTTT....TT.....
.....TT....TTTTTTTTTT....TT.....
.....TT....TTTTTTTTTT....TT.....
.....OO....TTTTTTTTTT....OO.....
.....OO....TTTTTTTTTT....OO.....
...........TTTTTTTTTT...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............OOOO.OOOO...........
................................
................................
`;

const PIXEL_POSES = {
  wave: POSE_WAVE,
  code: POSE_CODE,
  voice: POSE_VOICE,
  research: POSE_RESEARCH,
  lead: POSE_LEAD,
  win: POSE_WIN,
  study: POSE_STUDY,
  vr: POSE_VR,
};

function renderPixelArt(art, palette, pixelSize = 10) {
  const rows = art.split('\n').filter(r => r.length > 0);
  const rects = [];
  let key = 0;
  for (let y = 0; y < rows.length; y++) {
    const row = rows[y];
    for (let x = 0; x < row.length; x++) {
      const ch = row[x];
      if (ch === '.' || ch === ' ') continue;
      const fill = palette[ch];
      if (!fill) continue;
      rects.push(
        <rect key={key++}
              x={x * pixelSize} y={y * pixelSize}
              width={pixelSize} height={pixelSize}
              fill={fill}
              shapeRendering="crispEdges" />
      );
    }
  }
  return rects;
}

window.renderPixelArt = renderPixelArt;
window.PIXEL_POSES = PIXEL_POSES;
window.PIX_PALETTE_LIGHT = PIX_PALETTE_LIGHT;
window.PIX_PALETTE_DARK = PIX_PALETTE_DARK;
