// High-resolution pixel-art portrait for the menu — 40 cols × 56 rows at 8px = 320×448.
// Hand-tuned for the entry screen. Head + beard + torso are connected
// without gaps. Pose: front-facing portrait, slight implied shoulders.

const PIX_SILHOUETTE_MENU = `
........................................
........................................
............HHHHHHHHHHHH................
..........HHHHHHHHHHHHHHHH..............
.........HHHHHHHHHHHHHHHHHH.............
........HHHHHHHHHHHHHHHHHHHH............
.......HHHHSSSSSSSSSSSSSSHHHH...........
.......HHHSSSSSSSSSSSSSSSSHHH...........
.......HHSSSbbbbSSSSSSbbbbSSHH..........
.......HSSSbbbbbbSSSSbbbbbbSSH..........
.......HSSSEEEESSSSSSEEEESSSH..G........
.......HSSSEEEESSSSSSEEEESSSH..G........
.......HSSSSSSSSSSSSSSSSSSSSH...........
.......HSSSSSSSnnnnSSSSSSSSSH...........
.......HSSSSSSSnnnnnnSSSSSSSH...........
........HSSSSSSnnnnSSSSSSSSH............
........HHmmmmmmmmmmmmmmmmHH............
........HHHmmmmmmmmmmmmmHHH.............
.........HHBBBBBBBBBBBBBBHH.............
..........HBBBBBBBBBBBBBBH..............
...........BBBBBBBBBBBBBB...............
............BBBBBBBBBBBB................
.............BBBBBBBBBB.................
..............BBBBBBBB..................
..............SSSSSSSS..................
.............SSSSSSSSSS.................
............TTTTTTTTTTTT................
...........TTTTTTTTTTTTTT...............
..........TTTTTtttWWWtttTTTTT...........
..........TTTTtttTWWWTtttTTTT...........
.........TTTTTTTTTTTTTTTTTTTT...........
.........TTTTTTTTTTTTTTTTTTTT...........
.........TTTTTTTTTTTTTTTTTTTT...........
.........TTTTTTTTTTTTTTTTTTTT...........
.........TTTTTTTTTTTTTTTTTTTT...........
.........TTTTTTTTTTTTTTTTTTTT...........
.........TTTTTTTTTTTTTTTTTTTT...........
.........TTTTTTTTTTTTTTTTTTTT...........
.........TTTTTTTTTTTTTTTTTTTT...........
.........TTTTTTTTTTTTTTTTTTTT...........
..........TTTTTTTTTTTTTTTTTT............
...........TTTTTT....TTTTTT.............
..........PPPPPPP....PPPPPPP............
..........PPPPPPP....PPPPPPP............
..........PPPPPPP....PPPPPPP............
..........PPPPPPP....PPPPPPP............
..........PPPPPPP....PPPPPPP............
..........PPPPPPP....PPPPPPP............
..........PPPPPPP....PPPPPPP............
..........PPPPPPP....PPPPPPP............
.........OOOOOOOOO..OOOOOOOOO...........
.........OOOOOOOOO..OOOOOOOOO...........
........................................
........................................
........................................
........................................
`;

const PIX_SILHOUETTE_PALETTE = {
  H: '#1d1611',      // hair
  S: '#cda483',      // skin (face)
  s: '#a9805d',      // skin shade
  b: '#1d1611',      // brow
  E: '#0e0a06',      // eye
  n: '#a9805d',      // nose shading
  m: '#1d1611',      // moustache
  B: '#1d1611',      // beard
  T: '#1e8aa8',      // shirt
  t: '#136275',      // shirt shade / collar edge
  W: '#f4efe2',      // collar / paper
  P: '#1a1612',      // pants
  O: '#0a0807',      // shoes
  G: '#d2b16a',      // gold stud (left ear from his POV = viewer's right)
};

// Standing portrait — no wave, no props. Used on the entry-screen Lab portal.
const POSE_STAND = `
................................
................................
................................
................................
............HHHHHHHH............
...........HHHHHHHHHH...........
..........HHHHHHHHHHHH..........
..........HHHHHHHHHHHH..........
..........HSSSSSSSSSSH..........
..........HSbbSSSSbbSH..........
..........HSEESSEESSSH G........
..........HSSSSSSSSSSS..........
...........SSSSsSSSSSS..........
...........HMMMMMMMMMH..........
............HBBBBBBBH...........
............HBBBBBBBH...........
.............BBBBBBB............
..............BBBBB.............
..............SSSS..............
............TTTTTTTT............
...........TTTTTTTTTT...........
...........TTTWWWWTTT...........
..........TTTTTTTTTTTT..........
..........TTTTTTTTTTTT..........
..........TTTTTTTTTTTT..........
..........TTTTTTTTTTTT..........
..........TTTTTTTTTTTT..........
...........TTTTTTTTTT...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............PPPP.PPPP...........
............OOOO.OOOO...........
................................
................................
`;

window.POSE_STAND = POSE_STAND;
